// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeNkq4Liulj7hsDTq1Bpn6U-FxBKXopOA',
    appId: '1:495637881278:web:5e61f852c2ae47c4d119ef',
    messagingSenderId: '495637881278',
    projectId: 'dhealth-fb17e',
    authDomain: 'dhealth-fb17e.firebaseapp.com',
    storageBucket: 'dhealth-fb17e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1-Si6QAJjz0u-847OplR9UGHESJjwlpg',
    appId: '1:495637881278:android:a1d22a638b7e9427d119ef',
    messagingSenderId: '495637881278',
    projectId: 'dhealth-fb17e',
    storageBucket: 'dhealth-fb17e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJqty7WN3-zZozIicxW0_drGkYnaw3LBc',
    appId: '1:495637881278:ios:8a726ec5e8514c2bd119ef',
    messagingSenderId: '495637881278',
    projectId: 'dhealth-fb17e',
    storageBucket: 'dhealth-fb17e.firebasestorage.app',
    iosBundleId: 'com.example.dhealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJqty7WN3-zZozIicxW0_drGkYnaw3LBc',
    appId: '1:495637881278:ios:8a726ec5e8514c2bd119ef',
    messagingSenderId: '495637881278',
    projectId: 'dhealth-fb17e',
    storageBucket: 'dhealth-fb17e.firebasestorage.app',
    iosBundleId: 'com.example.dhealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeNkq4Liulj7hsDTq1Bpn6U-FxBKXopOA',
    appId: '1:495637881278:web:4302cca54a10458fd119ef',
    messagingSenderId: '495637881278',
    projectId: 'dhealth-fb17e',
    authDomain: 'dhealth-fb17e.firebaseapp.com',
    storageBucket: 'dhealth-fb17e.firebasestorage.app',
  );

}